### ISSUE TITLE
Overlapping strategy - update budget flow and design

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-app#1131]
prerequisite #948 

# Budget design update
This issue will outline a flow and design changes that will be applied on the deposit, withdraw and create **overlapping** strategy flows.

## Mockup
https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=14323-23752&mode=design&t=r7233fkw4bHiMa91-4

### Deposit (overlapping only)
Following the **exact** same flow as outlined in issue #948 with 1 difference:
- On step 2: **Edit budget**, remove the action toggle and only expose the option to **Deposit**
[deposit flow mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=14733-64884&mode=design&t=X0hrFXBNX04yQUIA-4)

### Withdrawal (overlapping only)
Following the **exact** same flow as outlined in issue #948 with 1 difference:
- On step 2: **Edit budget**, remove the action toggle and only expose the option to **Withdraw**
[withdrawal flow mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=14733-63761&mode=design&t=X0hrFXBNX04yQUIA-4)

### Create new strategy (overlapping only)
Following the **Deposit** flow (as new strategy always start with 0 budget and can only make a deposit), with the following difference:
- given allocation starts at 0, pay attention to the initial colors
[create overlapping strategy mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=14733-59911&mode=design&t=X0hrFXBNX04yQUIA-4)

**Comment by Leeseli** [comment]
Hi,
a minor design feedback
1. can you please reduce the top and bottom padding from 8px to 4? Because of the extra padding on top it looks very big.
<img width="491" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/159428318/64d41858-6b02-4f5e-87f5-2a1168b1d79b">

2. here please reduce the padding from 6 to 4.

<img width="451" alt="image" src="https://github.com/bancorprotocol/carbon-app/assets/159428318/837721b1-84ba-4d7a-a353-9fb655ce145c">

Thank you !
