### ISSUE TITLE
Trade - Order Book - more than one children with same key 

### ISSUE THREAD

**Issue by oznasi1** [bancorprotocol/carbon-app#414]
Probably need to find better id for order book children ( without rounding ) 
<img width="1882" alt="Screenshot 2023-03-12 at 14 58 06" src="https://user-images.githubusercontent.com/24458541/224546164-cd7e49bf-d6e8-475e-a6af-b19569429bd3.png">

**Comment by tiagofilipenunes** [comment]
Fixed in https://github.com/bancorprotocol/carbon-app/commit/a0a754673271052455df524c55d471c48178bd09. Rates are received from the SDK and should not be the same - down to the precision of decimal.js. Even if they were for a token with high number of decimals such as SHIB in the example, the key will always be unique.
