### ISSUE TITLE
It should be easy to build and deploy an app instance per chain

### ISSUE THREAD

**Issue by GrandSchtroumpf** [bancorprotocol/carbon-app#898]
The app can be run by any company for any chain. We should expose a single config file for developers to customize the app:
- Google Analytics
- Backend url
- chainId
- Contracts (voucher & controller)
- Popular token addresses
- CSS colors & fonts

**Comment by zavelevsky** [comment]
This is what I have in mind:

1. Place a config.json (or .ts) file in a specific location. This file is always there and always present. It is the file that code imports from and refers to - so that we can get proper auto completion and the IDE will not show errors in dev time.
2. Add a folder the contains config files that are chain specific. In our case, we will have config.ethereum.json placed there.
3. Move any chain specific stuff (that doesn't belong in env vars as a secret) to the config file, e.g. top tokens and their addresses, contract addresses etc.
4. the build script should support an optional CLI param specifying the config file name or path. It should be passed to the prebuild script which will copy the file and rename it so that it will override config.json (config.json should probably be in gitignore - or some other way to avoid unwanted changes)
5. Then when the app builds - it will be possible to build and deploy several instances - one per chain.
6. We don't have to make any changes to cloudflare pages because we will be using the default config

As for the contracts we are using, I believe that we can assume that the ABIs won't change between chains and we just need to move the addresses into the correct config file.

**Comment by GrandSchtroumpf** [comment]
This has been deprecated
